# Output config
temp_dir: 'tmp'
out_dir: 'output'

# Tissue name to ontology maps
cell_map: gs://genetics-portal-data/lut/biofeature_lut_190328.json

# Interval Liftover
chain_grch37_to_grch38: grch37_to_grch38.over.chain.gz
max_len_dff: 100 # Max difference in length between old and new interval (in bases)